version: '2'

services:
 java8:
  build: ./java8/
  tty: true
  environment:
    COMPOSE_HTTP_TIMEOUT: 200

 jenkins:
  build: ./jenkins/
  ports: 
    - "8080:8080"
  tty: true
  links:
   - java8
  environment:
   COMPOSE_HTTP_TIMEOUT: 200

 jira:
  build: ./jira/
  ports: 
   - "8081:8081"
  tty: true
  links:
   - java8
  environment:
    COMPOSE_HTTP_TIMEOUT: 200
  
 nexus:
  build: ./nexus/
  ports: 
   - "8082:8081" 
  tty: true
  links:
   - java8
  environment:
    COMPOSE_HTTP_TIMEOUT: 200
   
 zabbix:
  build: ./zabbix/
  ports: 
   - "80:80" 
  tty: true
  environment:
    COMPOSE_HTTP_TIMEOUT: 200
