version: '2'

services:
#java:
#build: ./java

#maven:
#build: ./maven

jenkins:
image: jenkis
build: ./jenkins
ports: 
- "8080:8080"
#links:
#- java

#jira:
#build: ./jira
#ports: 
- "8081:8081"
#links:
#- java