version: '2'

services:
 java8:
  build: ./java8/
  tty: true

 jenkins:
  build: ./jenkins/
  ports: 
    - "8080:8080"
  tty: true
  links:
   - java8

 jira:
  build: ./jira/
  ports: 
   - "8081:8081"
  tty: true
  links:
   - java8
  
 nexus:
  build: ./nexus/
  ports: 
   - "8082:8081" 
  tty: true
  links:
   - java8
   
 zabbix:
  build: ./zabbix/
  ports: 
   - "80:80" 
  tty: true

 tomcat:
  build: ./tomcat/
  ports: 
   - "8083:8080" 
  tty: true
  links:
   - java8
