version: '2'
services:
 #java:
   #build: ./java

  #maven:
   #build: ./maven

  jenkins:
   build: ./jenkins/
   ports: 
     - "8080:8080"
   #depends_on:
     #- java
   tty: true
   volumes:
    - /opt/jenkins:/var/lib/jenkins/

  #jira:
   #build: ./jira
   #ports: 
     #- "8081:8081"
   #depends_on:
     #- java
