# docker file to run and build programs
FROM ubuntu:16.04
MAINTAINER MikeyB

CMD /bin/bash

RUN apt-get update -y
RUN apt-get install -y git
RUN apt-get install -y wget

#RUN git clone https://github.com/mikeyb11/DockerAWS.git
     
#RUN tar -zxvf jdk-8u111-linux-x64.tar.gz

#RUN cp jdk-8u111

#RUN java -version
